export const GUEST_TOKEN = 'guest-token';
export const USER_TOKEN = 'user-token';
export const NO_SUPPORT = 'NO_SUPPORT';
export const DEFAULT_ERROR_CODE = 400;
export const SW_IGNORE = ['embed/*'];
export const CHARMBOARD_PLUGIN_URL = 'https://cbstatic.charmboard.com/cb_plugin/hipi_plugin_v1.0.1_min.js';
export const API_KEY_SHOP = 'HVKJWV0-6V4MYV1-NBT0TBD-PM9EBTF';
export const GOOGLE_ONE_TAP = 'https://accounts.google.com/gsi/client';
export const GOOGLE_PLATFORM = 'https://apis.google.com/js/platform.js';
export const MIXPANEL_DEV = 'b37fe42d0dbab8e70c17b411d0c47022';
export const MIXPANEL_PROD = '28ad1bd3f9fbcda7356c70835a0b4d96';
export const ONE_TAP_DOWNLOAD = 'https://hipi.onelink.me/tMco/1e3e4b5e';
export const BASIC_ONE_LINK_SKELETON = 'https://hipi.onelink.me/tMco'
export const DYNAMIC_ONE_TAP_DOWNLOAD = 'https://onelink.appsflyer.com/shortlink/v1/tMco';
export const ANDROID_STORE = 'https://play.google.com/store/apps/details?id=com.zee5.hipi';
export const IOS_STORE = 'https://apps.apple.com/in/app/hipi-indian-short-video-app/id1561950008';
export const VERSION = '5.1.2';
export const APP_NAME = 'HiPi';
export const APP_ID = "YInJ8G70y098";
export const LANGUAGE = 'en';
export const GOOGLE_CLIENT_ID_PREROD = '1026747734321-0fobt02rbhi5j36kk6ft8el2k0tev9af.apps.googleusercontent.com';
export const GOOGLE_CLIENT_ID_LOCAL = '1089855202811-en5ek78kvh7sst9bfmu62femgr15u0tk.apps.googleusercontent.com';
export const FACEBOOK_PIXEL_ID = '493676215515717'
export const DISCOVER_SEARCH_RESULTS = 'Discover Search Results'
export const CREATOR_PROFILE = 'Creator Profile'
export const SEARCH_EVENT = 'search_event';
export const FULL_EXPERIENCE = 'Get the full experience on the Hipi app';
export const TEST_CUSTOMER_KEY = '68b23e5e4a3770c20f04989fa8e89e0872e1c843';
export const CONVIVA_PROD_CUSTOMER_KEY = '28bbf0a3decf6d1165032bfd835d6e1844c5d44d';
export const TOUCHSTONE_SERVICE_URL = 'https://zee-test.testonly.conviva.com';
export const STORYBLOK_TOKEN = 'quNBuDdvpWQyR7qL35OGjwtt'
export const STATIC_PAGE_CREATOR_KEY = '1EC97-25A91-DAA24-FF3CA4-4LD8D-OFB84';
export const INDEX_TO_SHOW_LANG = 5;
export const INDEX_TO_SHOW_LANG_IPHONE = 5;
export const SITE_ID = "hipi";
export const S3_POOL_ID = 'ap-south-1:ed544dca-9139-40ad-90ab-22fe06a98d10';
export const S3_REGION = 'ap-south-1';
export const S3_BUCKET_STAGE = 'hipi-videos-stage'
export const S3_BUCKET_PROD = 'hipi-videos'
export const UPLOAD_ACCESS_USERS = ["Tamil360","MiniatureFoods","WanderessKriti","Aditi_Prabhudeva", "bharatjangid3649", "murali.teams","anuragguptazee","16cf2063", "khushi_angel"]
export const ESK_ENV = 'preprod';