export const GUEST_TOKEN = 'guest-token';
export const USER_TOKEN = 'user-token';
export const NO_SUPPORT = 'NO_SUPPORT';
export const DEFAULT_ERROR_CODE = 400;
export const SW_IGNORE = ['embed/*'];
export const CHARMBOARD_PLUGIN_URL = 'https://cbstatic.charmboard.com/cb_plugin/hipi_plugin_v1.0.1_min.js';
export const API_KEY_SHOP = 'HVKJWV0-6V4MYV1-NBT0TBD-PM9EBTF';
export const GOOGLE_ONE_TAP = 'https://accounts.google.com/gsi/client';
export const GOOGLE_PLATFORM = 'https://apis.google.com/js/platform.js';
export const MIXPANEL_DEV = 'b37fe42d0dbab8e70c17b411d0c47022';
export const MIXPANEL_PROD = '28ad1bd3f9fbcda7356c70835a0b4d96';
export const ONE_TAP_DOWNLOAD = 'https://hipi.onelink.me/tMco/1e3e4b5e';
export const ANDROID_STORE = 'https://play.google.com/store/apps/details?id=com.zee5.hipi';
export const IOS_STORE = 'https://apps.apple.com/in/app/hipi-indian-short-video-app/id1561950008';
export const VERSION = '1.1.6';
export const APP_NAME = 'HiPi';
export const LANGUAGE = 'en'
