name: Test site for publicly known js vulnerabilities

on:
  push:
    branches: [ develop, release, master ]
  pull_request:
    branches: [ develop, release, master ]
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://yoursite.com"
